package elementalweapons;

import legend.core.GameEngine;
import legend.game.characters.ElementSet;
import legend.game.inventory.Equipment;
import legend.game.inventory.EquipmentRegistryEvent;
import legend.game.inventory.ItemIcon;
import legend.game.types.EquipmentSlot;
import legend.lodmod.LodMod;
import org.legendofdragoon.modloader.registries.Registrar;
import org.legendofdragoon.modloader.registries.RegistryDelegate;

public class Equipments {
  private Equipments() { }

  private static final Registrar<Equipment, EquipmentRegistryEvent> EQUIPMENT_REGISTRAR = new Registrar<>(GameEngine.REGISTRIES.equipment, ElementalWeapons.MOD_ID);

  // DART
  public static final RegistryDelegate<Equipment> DAMP_BLADE = EQUIPMENT_REGISTRAR.register("damp_blade", () -> new Equipment(80, 0x0, EquipmentSlot.WEAPON, LodMod.WATER_ELEMENT.get(), new ElementSet(), new ElementSet(), 0x0, 10, 0, 0, 0, 0, 0, 0, 0, false, false, false, false, 0, 0, 0, 0, 0, ItemIcon.SWORD, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0x0));
  public static final RegistryDelegate<Equipment> WATER_BROADSWORD = EQUIPMENT_REGISTRAR.register("water_broadsword", () -> new Equipment(250, 0x0, EquipmentSlot.WEAPON, LodMod.WATER_ELEMENT.get(), new ElementSet(), new ElementSet(), 0x0, 30, 0, 0, 0, 0, 0, 0, 0, false, false, false, false, 0, 0, 0, 0, 0, ItemIcon.SWORD, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0x0));
  public static final RegistryDelegate<Equipment> OCEAN_GREATSWORD = EQUIPMENT_REGISTRAR.register("ocean_greatsword", () -> new Equipment(400, 0x0, EquipmentSlot.WEAPON, LodMod.WATER_ELEMENT.get(), new ElementSet(), new ElementSet(), 0x0, 42, 0, 0, 0, 0, 0, 0, 0, false, false, false, false, 0, 0, 0, 0, 0, ItemIcon.SWORD, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0x0));
  public static final RegistryDelegate<Equipment> BLAZING_BROADSWORD = EQUIPMENT_REGISTRAR.register("blazing_broadsword", () -> new Equipment(250, 0x0, EquipmentSlot.WEAPON, LodMod.FIRE_ELEMENT.get(), new ElementSet(), new ElementSet(), 0x0, 30, 0, 0, 0, 0, 0, 0, 0, false, false, false, false, 0, 0, 0, 0, 0, ItemIcon.SWORD, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0x0));
  public static final RegistryDelegate<Equipment> INFERNO_GREATSWORD = EQUIPMENT_REGISTRAR.register("inferno_greatsword", () -> new Equipment(400, 0x0, EquipmentSlot.WEAPON, LodMod.FIRE_ELEMENT.get(), new ElementSet(), new ElementSet(), 0x0, 42, 0, 0, 0, 0, 0, 0, 0, false, false, false, false, 0, 0, 0, 0, 0, ItemIcon.SWORD, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0x0));
  public static final RegistryDelegate<Equipment> GUST_LONGSWORD = EQUIPMENT_REGISTRAR.register("gust_longsword", () -> new Equipment(250, 0x0, EquipmentSlot.WEAPON, LodMod.WIND_ELEMENT.get(), new ElementSet(), new ElementSet(), 0x0, 24, 0, 0, 0, 0, 0, 0, 0, false, false, false, false, 0, 0, 0, 0, 0, ItemIcon.SWORD, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0x0));
  public static final RegistryDelegate<Equipment> GRAVEL_LONGSWORD = EQUIPMENT_REGISTRAR.register("gravel_longsword", () -> new Equipment(250, 0x0, EquipmentSlot.WEAPON, LodMod.EARTH_ELEMENT.get(), new ElementSet(), new ElementSet(), 0x0, 24, 0, 0, 0, 0, 0, 0, 0, false, false, false, false, 0, 0, 0, 0, 0, ItemIcon.SWORD, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0x0));
  public static final RegistryDelegate<Equipment> GLOWING_BLADE = EQUIPMENT_REGISTRAR.register("glowing_blade", () -> new Equipment(210, 0x0, EquipmentSlot.WEAPON, LodMod.LIGHT_ELEMENT.get(), new ElementSet(), new ElementSet(), 0x0, 24, 0, 0, 0, 0, 0, 0, 0, false, false, false, false, 0, 0, 0, 0, 0, ItemIcon.SWORD, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0x0));
  public static final RegistryDelegate<Equipment> BLACK_BLADE = EQUIPMENT_REGISTRAR.register("black_blade", () -> new Equipment(210, 0x0, EquipmentSlot.WEAPON, LodMod.DARK_ELEMENT.get(), new ElementSet(), new ElementSet(), 0x0, 24, 0, 0, 0, 0, 0, 0, 0, false, false, false, false, 0, 0, 0, 0, 0, ItemIcon.SWORD, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0x0));
  public static final RegistryDelegate<Equipment> SHOCKING_BROADBLADE = EQUIPMENT_REGISTRAR.register("shocking_broadblade", () -> new Equipment(250, 0x0, EquipmentSlot.WEAPON, LodMod.THUNDER_ELEMENT.get(), new ElementSet(), new ElementSet(), 0x0, 30, 0, 0, 0, 0, 0, 0, 0, false, false, false, false, 0, 0, 0, 0, 0, ItemIcon.SWORD, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0x0));
  public static final RegistryDelegate<Equipment> HURRICANE_CLAYMORE = EQUIPMENT_REGISTRAR.register("hurricane_claymore", () -> new Equipment(400, 0x0, EquipmentSlot.WEAPON, LodMod.WIND_ELEMENT.get(), new ElementSet(), new ElementSet(), 0x0, 42, 0, 0, 0, 0, 0, 0, 0, false, false, false, false, 0, 0, 0, 0, 0, ItemIcon.SWORD, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0x0));
  public static final RegistryDelegate<Equipment> STONE_CLAYMORE = EQUIPMENT_REGISTRAR.register("stone_claymore", () -> new Equipment(400, 0x0, EquipmentSlot.WEAPON, LodMod.EARTH_ELEMENT.get(), new ElementSet(), new ElementSet(), 0x0, 42, 0, 0, 0, 0, 0, 0, 0, false, false, false, false, 0, 0, 0, 0, 0, ItemIcon.SWORD, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0x0));
  public static final RegistryDelegate<Equipment> BLINDING_ZWEIHANDER = EQUIPMENT_REGISTRAR.register("blinding_zweihander", () -> new Equipment(400, 0x0, EquipmentSlot.WEAPON, LodMod.LIGHT_ELEMENT.get(), new ElementSet(), new ElementSet(), 0x0, 42, 0, 0, 0, 0, 0, 0, 0, false, false, false, false, 0, 0, 0, 0, 0, ItemIcon.SWORD, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0x0));
  public static final RegistryDelegate<Equipment> NIGHT_ZWEIHANDER = EQUIPMENT_REGISTRAR.register("night_zweihander", () -> new Equipment(400, 0x0, EquipmentSlot.WEAPON, LodMod.DARK_ELEMENT.get(), new ElementSet(), new ElementSet(), 0x0, 42, 0, 0, 0, 0, 0, 0, 0, false, false, false, false, 0, 0, 0, 0, 0, ItemIcon.SWORD, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0x0));
  public static final RegistryDelegate<Equipment> LIGHTNING_GREATBLADE = EQUIPMENT_REGISTRAR.register("lightning_greatblade", () -> new Equipment(400, 0x0, EquipmentSlot.WEAPON, LodMod.THUNDER_ELEMENT.get(), new ElementSet(), new ElementSet(), 0x0, 42, 0, 0, 0, 0, 0, 0, 0, false, false, false, false, 0, 0, 0, 0, 0, ItemIcon.SWORD, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0x0));

  // LAVITZ-ALBERT
  public static final RegistryDelegate<Equipment> VORTEX_GLAIVE = EQUIPMENT_REGISTRAR.register("vortex_glaive", () -> new Equipment(400, 0x0, EquipmentSlot.WEAPON, LodMod.WIND_ELEMENT.get(), new ElementSet(), new ElementSet(), 0x0, 60, 0, 0, 0, 0, 0, 0, 0, false, false, false, false, 0, 0, 0, 0, 0, ItemIcon.SPEAR, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0x0));
  public static final RegistryDelegate<Equipment> STONE_LANCE = EQUIPMENT_REGISTRAR.register("stone_lance", () -> new Equipment(210, 0x0, EquipmentSlot.WEAPON, LodMod.EARTH_ELEMENT.get(), new ElementSet(), new ElementSet(), 0x0, 32, 0, 0, 0, 0, 0, 0, 0, false, false, false, false, 0, 0, 0, 0, 0, ItemIcon.SPEAR, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0x0));
  public static final RegistryDelegate<Equipment> CANYON_LANCE = EQUIPMENT_REGISTRAR.register("canyon_lance", () -> new Equipment(400, 0x0, EquipmentSlot.WEAPON, LodMod.EARTH_ELEMENT.get(), new ElementSet(), new ElementSet(), 0x0, 60, 0, 0, 0, 0, 0, 0, 0, false, false, false, false, 0, 0, 0, 0, 0, ItemIcon.SPEAR, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0x0));
  public static final RegistryDelegate<Equipment> BURNING_PARTISAN = EQUIPMENT_REGISTRAR.register("burning_partisan", () -> new Equipment(250, 0x0, EquipmentSlot.WEAPON, LodMod.FIRE_ELEMENT.get(), new ElementSet(), new ElementSet(), 0x0, 41, 0, 0, 0, 0, 0, 0, 0, false, false, false, false, 0, 0, 0, 0, 0, ItemIcon.SPEAR, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0x0));
  public static final RegistryDelegate<Equipment> LIQUID_SPEAR = EQUIPMENT_REGISTRAR.register("liquid_spear", () -> new Equipment(250, 0x0, EquipmentSlot.WEAPON, LodMod.WATER_ELEMENT.get(), new ElementSet(), new ElementSet(), 0x0, 41, 0, 0, 0, 0, 0, 0, 0, false, false, false, false, 0, 0, 0, 0, 0, ItemIcon.SPEAR, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0x0));
  public static final RegistryDelegate<Equipment> BRIGHT_HALBERD = EQUIPMENT_REGISTRAR.register("bright_halberd", () -> new Equipment(210, 0x0, EquipmentSlot.WEAPON, LodMod.LIGHT_ELEMENT.get(), new ElementSet(), new ElementSet(), 0x0, 32, 0, 0, 0, 0, 0, 0, 0, false, false, false, false, 0, 0, 0, 0, 0, ItemIcon.SPEAR, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0x0));
  public static final RegistryDelegate<Equipment> DARK_HALBERD = EQUIPMENT_REGISTRAR.register("dark_halberd", () -> new Equipment(210, 0x0, EquipmentSlot.WEAPON, LodMod.DARK_ELEMENT.get(), new ElementSet(), new ElementSet(), 0x0, 32, 0, 0, 0, 0, 0, 0, 0, false, false, false, false, 0, 0, 0, 0, 0, ItemIcon.SPEAR, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0x0));
  public static final RegistryDelegate<Equipment> ELECTRIC_SWORDLANCE = EQUIPMENT_REGISTRAR.register("electric_swordlance", () -> new Equipment(250, 0x0, EquipmentSlot.WEAPON, LodMod.THUNDER_ELEMENT.get(), new ElementSet(), new ElementSet(), 0x0, 41, 0, 0, 0, 0, 0, 0, 0, false, false, false, false, 0, 0, 0, 0, 0, ItemIcon.SPEAR, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0x0));
  public static final RegistryDelegate<Equipment> FLAMING_PARTISAN = EQUIPMENT_REGISTRAR.register("flaming_partisan", () -> new Equipment(400, 0x0, EquipmentSlot.WEAPON, LodMod.FIRE_ELEMENT.get(), new ElementSet(), new ElementSet(), 0x0, 60, 0, 0, 0, 0, 0, 0, 0, false, false, false, false, 0, 0, 0, 0, 0, ItemIcon.SPEAR, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0x0));
  public static final RegistryDelegate<Equipment> WHIRLPOOL_SPEAR = EQUIPMENT_REGISTRAR.register("whirlpool_spear", () -> new Equipment(400, 0x0, EquipmentSlot.WEAPON, LodMod.WATER_ELEMENT.get(), new ElementSet(), new ElementSet(), 0x0, 60, 0, 0, 0, 0, 0, 0, 0, false, false, false, false, 0, 0, 0, 0, 0, ItemIcon.SPEAR, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0x0));
  public static final RegistryDelegate<Equipment> DAWN_HALBERD = EQUIPMENT_REGISTRAR.register("dawn_halberd", () -> new Equipment(400, 0x0, EquipmentSlot.WEAPON, LodMod.LIGHT_ELEMENT.get(), new ElementSet(), new ElementSet(), 0x0, 60, 0, 0, 0, 0, 0, 0, 0, false, false, false, false, 0, 0, 0, 0, 0, ItemIcon.SPEAR, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0x0));
  public static final RegistryDelegate<Equipment> DUSK_HALBERD = EQUIPMENT_REGISTRAR.register("dusk_halberd", () -> new Equipment(400, 0x0, EquipmentSlot.WEAPON, LodMod.DARK_ELEMENT.get(), new ElementSet(), new ElementSet(), 0x0, 60, 0, 0, 0, 0, 0, 0, 0, false, false, false, false, 0, 0, 0, 0, 0, ItemIcon.SPEAR, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0x0));
  public static final RegistryDelegate<Equipment> CURRENT_SWORDLANCE = EQUIPMENT_REGISTRAR.register("current_swordlance", () -> new Equipment(400, 0x0, EquipmentSlot.WEAPON, LodMod.THUNDER_ELEMENT.get(), new ElementSet(), new ElementSet(), 0x0, 60, 0, 0, 0, 0, 0, 0, 0, false, false, false, false, 0, 0, 0, 0, 0, ItemIcon.SPEAR, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0x0));

  // SHANA-MIRANDA
  public static final RegistryDelegate<Equipment> SHINING_ARROW = EQUIPMENT_REGISTRAR.register("shining_arrow", () -> new Equipment(210, 0x0, EquipmentSlot.WEAPON, LodMod.LIGHT_ELEMENT.get(), new ElementSet(), new ElementSet(), 0x0, 22, 0, 0, 0, 0, 0, 0, 0, false, false, false, false, 0, 0, 0, 0, 0, ItemIcon.BOW, 0, 0, 0, 0, 0, 20, 0, 0, 0, 0, 0x0));
  public static final RegistryDelegate<Equipment> HEAVEN_BOW = EQUIPMENT_REGISTRAR.register("heaven_bow", () -> new Equipment(400, 0x0, EquipmentSlot.WEAPON, LodMod.LIGHT_ELEMENT.get(), new ElementSet(), new ElementSet(), 0x0, 44, 0, 0, 0, 0, 0, 0, 0, false, false, false, false, 0, 0, 0, 0, 0, ItemIcon.BOW, 0, 0, 0, 0, 0, 20, 0, 0, 0, 0, 0x0));
  public static final RegistryDelegate<Equipment> BLINDING_ARROW = EQUIPMENT_REGISTRAR.register("blinding_arrow", () -> new Equipment(210, 0x0, EquipmentSlot.WEAPON, LodMod.DARK_ELEMENT.get(), new ElementSet(), new ElementSet(), 0x0, 22, 0, 0, 0, 0, 0, 0, 0, false, false, false, false, 0, 0, 0, 0, 0, ItemIcon.BOW, 0, 0, 0, 0, 0, 20, 0, 0, 0, 0, 0x0));
  public static final RegistryDelegate<Equipment> HELL_BOW = EQUIPMENT_REGISTRAR.register("hell_bow", () -> new Equipment(400, 0x0, EquipmentSlot.WEAPON, LodMod.DARK_ELEMENT.get(), new ElementSet(), new ElementSet(), 0x0, 44, 0, 0, 0, 0, 0, 0, 0, false, false, false, false, 0, 0, 0, 0, 0, ItemIcon.BOW, 0, 0, 0, 0, 0, 20, 0, 0, 0, 0, 0x0));
  public static final RegistryDelegate<Equipment> SMOLDERING_ARROW = EQUIPMENT_REGISTRAR.register("smoldering_arrow", () -> new Equipment(250, 0x0, EquipmentSlot.WEAPON, LodMod.FIRE_ELEMENT.get(), new ElementSet(), new ElementSet(), 0x0, 27, 0, 0, 0, 0, 0, 0, 0, false, false, false, false, 0, 0, 0, 0, 0, ItemIcon.BOW, 0, 0, 0, 0, 0, 20, 0, 0, 0, 0, 0x0));
  public static final RegistryDelegate<Equipment> SPLASHING_ARROW = EQUIPMENT_REGISTRAR.register("splashing_arrow", () -> new Equipment(250, 0x0, EquipmentSlot.WEAPON, LodMod.WATER_ELEMENT.get(), new ElementSet(), new ElementSet(), 0x0, 27, 0, 0, 0, 0, 0, 0, 0, false, false, false, false, 0, 0, 0, 0, 0, ItemIcon.BOW, 0, 0, 0, 0, 0, 20, 0, 0, 0, 0, 0x0));
  public static final RegistryDelegate<Equipment> AIR_ARROW = EQUIPMENT_REGISTRAR.register("air_arrow", () -> new Equipment(210, 0x0, EquipmentSlot.WEAPON, LodMod.WIND_ELEMENT.get(), new ElementSet(), new ElementSet(), 0x0, 22, 0, 0, 0, 0, 0, 0, 0, false, false, false, false, 0, 0, 0, 0, 0, ItemIcon.BOW, 0, 0, 0, 0, 0, 20, 0, 0, 0, 0, 0x0));
  public static final RegistryDelegate<Equipment> ROCK_ARROW = EQUIPMENT_REGISTRAR.register("rock_arrow", () -> new Equipment(210, 0x0, EquipmentSlot.WEAPON, LodMod.EARTH_ELEMENT.get(), new ElementSet(), new ElementSet(), 0x0, 22, 0, 0, 0, 0, 0, 0, 0, false, false, false, false, 0, 0, 0, 0, 0, ItemIcon.BOW, 0, 0, 0, 0, 0, 20, 0, 0, 0, 0, 0x0));
  public static final RegistryDelegate<Equipment> STINGING_ARROW = EQUIPMENT_REGISTRAR.register("stinging_arrow", () -> new Equipment(250, 0x0, EquipmentSlot.WEAPON, LodMod.THUNDER_ELEMENT.get(), new ElementSet(), new ElementSet(), 0x0, 27, 0, 0, 0, 0, 0, 0, 0, false, false, false, false, 0, 0, 0, 0, 0, ItemIcon.BOW, 0, 0, 0, 0, 0, 20, 0, 0, 0, 0, 0x0));
  public static final RegistryDelegate<Equipment> COMBUSTION_BOW = EQUIPMENT_REGISTRAR.register("combustion_bow", () -> new Equipment(400, 0x0, EquipmentSlot.WEAPON, LodMod.FIRE_ELEMENT.get(), new ElementSet(), new ElementSet(), 0x0, 44, 0, 0, 0, 0, 0, 0, 0, false, false, false, false, 0, 0, 0, 0, 0, ItemIcon.BOW, 0, 0, 0, 0, 0, 20, 0, 0, 0, 0, 0x0));
  public static final RegistryDelegate<Equipment> DROWNING_BOW = EQUIPMENT_REGISTRAR.register("drowning_bow", () -> new Equipment(400, 0x0, EquipmentSlot.WEAPON, LodMod.WATER_ELEMENT.get(), new ElementSet(), new ElementSet(), 0x0, 44, 0, 0, 0, 0, 0, 0, 0, false, false, false, false, 0, 0, 0, 0, 0, ItemIcon.BOW, 0, 0, 0, 0, 0, 20, 0, 0, 0, 0, 0x0));
  public static final RegistryDelegate<Equipment> WIND_BOW = EQUIPMENT_REGISTRAR.register("wind_bow", () -> new Equipment(400, 0x0, EquipmentSlot.WEAPON, LodMod.WIND_ELEMENT.get(), new ElementSet(), new ElementSet(), 0x0, 44, 0, 0, 0, 0, 0, 0, 0, false, false, false, false, 0, 0, 0, 0, 0, ItemIcon.BOW, 0, 0, 0, 0, 0, 20, 0, 0, 0, 0, 0x0));
  public static final RegistryDelegate<Equipment> BOULDER_BOW = EQUIPMENT_REGISTRAR.register("boulder_bow", () -> new Equipment(400, 0x0, EquipmentSlot.WEAPON, LodMod.EARTH_ELEMENT.get(), new ElementSet(), new ElementSet(), 0x0, 44, 0, 0, 0, 0, 0, 0, 0, false, false, false, false, 0, 0, 0, 0, 0, ItemIcon.BOW, 0, 0, 0, 0, 0, 20, 0, 0, 0, 0, 0x0));
  public static final RegistryDelegate<Equipment> TINGLING_BOW = EQUIPMENT_REGISTRAR.register("tingling_bow", () -> new Equipment(400, 0x0, EquipmentSlot.WEAPON, LodMod.THUNDER_ELEMENT.get(), new ElementSet(), new ElementSet(), 0x0, 44, 0, 0, 0, 0, 0, 0, 0, false, false, false, false, 0, 0, 0, 0, 0, ItemIcon.BOW, 0, 0, 0, 0, 0, 20, 0, 0, 0, 0, 0x0));

  // ROSE
  public static final RegistryDelegate<Equipment> DARKNESS_SHEARER = EQUIPMENT_REGISTRAR.register("darkness_shearer", () -> new Equipment(400, 0x0, EquipmentSlot.WEAPON, LodMod.DARK_ELEMENT.get(), new ElementSet(), new ElementSet(), 0x0, 55, 0, 0, 0, 0, 0, 0, 0, false, false, false, false, 0, 0, 0, 0, 0, ItemIcon.SWORD, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0x0));
  public static final RegistryDelegate<Equipment> SHINING_LIGHT = EQUIPMENT_REGISTRAR.register("shining_light", () -> new Equipment(210, 0x0, EquipmentSlot.WEAPON, LodMod.LIGHT_ELEMENT.get(), new ElementSet(), new ElementSet(), 0x0, 27, 0, 0, 0, 0, 0, 0, 0, false, false, false, false, 0, 0, 0, 0, 0, ItemIcon.SWORD, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0x0));
  public static final RegistryDelegate<Equipment> LIGHT_BRINGER = EQUIPMENT_REGISTRAR.register("light_bringer", () -> new Equipment(400, 0x0, EquipmentSlot.WEAPON, LodMod.LIGHT_ELEMENT.get(), new ElementSet(), new ElementSet(), 0x0, 55, 0, 0, 0, 0, 0, 0, 0, false, false, false, false, 0, 0, 0, 0, 0, ItemIcon.SWORD, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0x0));
  public static final RegistryDelegate<Equipment> EMBERS_GLOW = EQUIPMENT_REGISTRAR.register("embers_glow", () -> new Equipment(250, 0x0, EquipmentSlot.WEAPON, LodMod.FIRE_ELEMENT.get(), new ElementSet(), new ElementSet(), 0x0, 32, 0, 0, 0, 0, 0, 0, 0, false, false, false, false, 0, 0, 0, 0, 0, ItemIcon.SWORD, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0x0));
  public static final RegistryDelegate<Equipment> WATERS_EDGE = EQUIPMENT_REGISTRAR.register("waters_edge", () -> new Equipment(250, 0x0, EquipmentSlot.WEAPON, LodMod.WATER_ELEMENT.get(), new ElementSet(), new ElementSet(), 0x0, 32, 0, 0, 0, 0, 0, 0, 0, false, false, false, false, 0, 0, 0, 0, 0, ItemIcon.SWORD, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0x0));
  public static final RegistryDelegate<Equipment> WINDS_LAMENT = EQUIPMENT_REGISTRAR.register("winds_lament", () -> new Equipment(210, 0x0, EquipmentSlot.WEAPON, LodMod.WIND_ELEMENT.get(), new ElementSet(), new ElementSet(), 0x0, 27, 0, 0, 0, 0, 0, 0, 0, false, false, false, false, 0, 0, 0, 0, 0, ItemIcon.SWORD, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0x0));
  public static final RegistryDelegate<Equipment> EARTHS_ETUDE = EQUIPMENT_REGISTRAR.register("earths_etude", () -> new Equipment(210, 0x0, EquipmentSlot.WEAPON, LodMod.EARTH_ELEMENT.get(), new ElementSet(), new ElementSet(), 0x0, 27, 0, 0, 0, 0, 0, 0, 0, false, false, false, false, 0, 0, 0, 0, 0, ItemIcon.SWORD, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0x0));
  public static final RegistryDelegate<Equipment> THUNDER_CRACK = EQUIPMENT_REGISTRAR.register("thunder_crack", () -> new Equipment(250, 0x0, EquipmentSlot.WEAPON, LodMod.THUNDER_ELEMENT.get(), new ElementSet(), new ElementSet(), 0x0, 32, 0, 0, 0, 0, 0, 0, 0, false, false, false, false, 0, 0, 0, 0, 0, ItemIcon.SWORD, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0x0));
  public static final RegistryDelegate<Equipment> FIRES_ROAR = EQUIPMENT_REGISTRAR.register("fires_roar", () -> new Equipment(400, 0x0, EquipmentSlot.WEAPON, LodMod.FIRE_ELEMENT.get(), new ElementSet(), new ElementSet(), 0x0, 55, 0, 0, 0, 0, 0, 0, 0, false, false, false, false, 0, 0, 0, 0, 0, ItemIcon.SWORD, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0x0));
  public static final RegistryDelegate<Equipment> RIVERS_FLOW = EQUIPMENT_REGISTRAR.register("rivers_flow", () -> new Equipment(400, 0x0, EquipmentSlot.WEAPON, LodMod.WATER_ELEMENT.get(), new ElementSet(), new ElementSet(), 0x0, 55, 0, 0, 0, 0, 0, 0, 0, false, false, false, false, 0, 0, 0, 0, 0, ItemIcon.SWORD, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0x0));
  public static final RegistryDelegate<Equipment> AIRS_REQUIEM = EQUIPMENT_REGISTRAR.register("airs_requiem", () -> new Equipment(400, 0x0, EquipmentSlot.WEAPON, LodMod.WIND_ELEMENT.get(), new ElementSet(), new ElementSet(), 0x0, 55, 0, 0, 0, 0, 0, 0, 0, false, false, false, false, 0, 0, 0, 0, 0, ItemIcon.SWORD, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0x0));
  public static final RegistryDelegate<Equipment> MOUNTAINS_DIRGE = EQUIPMENT_REGISTRAR.register("mountains_dirge", () -> new Equipment(400, 0x0, EquipmentSlot.WEAPON, LodMod.EARTH_ELEMENT.get(), new ElementSet(), new ElementSet(), 0x0, 55, 0, 0, 0, 0, 0, 0, 0, false, false, false, false, 0, 0, 0, 0, 0, ItemIcon.SWORD, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0x0));
  public static final RegistryDelegate<Equipment> LIGHTNING_REPRISE = EQUIPMENT_REGISTRAR.register("lightning_reprise", () -> new Equipment(400, 0x0, EquipmentSlot.WEAPON, LodMod.THUNDER_ELEMENT.get(), new ElementSet(), new ElementSet(), 0x0, 55, 0, 0, 0, 0, 0, 0, 0, false, false, false, false, 0, 0, 0, 0, 0, ItemIcon.SWORD, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0x0));

  // HASCHEL
  public static final RegistryDelegate<Equipment> STATIC_KNUCKLES = EQUIPMENT_REGISTRAR.register("static_knuckles", () -> new Equipment(100, 0x0, EquipmentSlot.WEAPON, LodMod.THUNDER_ELEMENT.get(), new ElementSet(), new ElementSet(), 0x0, 26, 0, 0, 0, 0, 0, 0, 0, false, false, false, false, 0, 0, 0, 0, 0, ItemIcon.KNUCKLE, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0x0));
  public static final RegistryDelegate<Equipment> STORM_FIST = EQUIPMENT_REGISTRAR.register("storm_fist", () -> new Equipment(250, 0x0, EquipmentSlot.WEAPON, LodMod.THUNDER_ELEMENT.get(), new ElementSet(), new ElementSet(), 0x0, 34, 0, 0, 0, 0, 0, 0, 0, false, false, false, false, 0, 0, 0, 0, 0, ItemIcon.BOXING_GLOVE, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0x0));
  public static final RegistryDelegate<Equipment> FLAMING_FIST = EQUIPMENT_REGISTRAR.register("flaming_fist", () -> new Equipment(250, 0x0, EquipmentSlot.WEAPON, LodMod.FIRE_ELEMENT.get(), new ElementSet(), new ElementSet(), 0x0, 34, 0, 0, 0, 0, 0, 0, 0, false, false, false, false, 0, 0, 0, 0, 0, ItemIcon.BOXING_GLOVE, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0x0));
  public static final RegistryDelegate<Equipment> RAPIDS_FIST = EQUIPMENT_REGISTRAR.register("rapids_fist", () -> new Equipment(250, 0x0, EquipmentSlot.WEAPON, LodMod.WATER_ELEMENT.get(), new ElementSet(), new ElementSet(), 0x0, 34, 0, 0, 0, 0, 0, 0, 0, false, false, false, false, 0, 0, 0, 0, 0, ItemIcon.BOXING_GLOVE, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0x0));
  public static final RegistryDelegate<Equipment> FLEETING_FIST = EQUIPMENT_REGISTRAR.register("fleeting_fist", () -> new Equipment(210, 0x0, EquipmentSlot.WEAPON, LodMod.WIND_ELEMENT.get(), new ElementSet(), new ElementSet(), 0x0, 34, 0, 0, 0, 0, 0, 0, 0, false, false, false, false, 0, 0, 0, 0, 0, ItemIcon.BOXING_GLOVE, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0x0));
  public static final RegistryDelegate<Equipment> STURDY_FIST = EQUIPMENT_REGISTRAR.register("sturdy_fist", () -> new Equipment(210, 0x0, EquipmentSlot.WEAPON, LodMod.EARTH_ELEMENT.get(), new ElementSet(), new ElementSet(), 0x0, 34, 0, 0, 0, 0, 0, 0, 0, false, false, false, false, 0, 0, 0, 0, 0, ItemIcon.BOXING_GLOVE, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0x0));
  public static final RegistryDelegate<Equipment> FLASHY_FIST = EQUIPMENT_REGISTRAR.register("flashy_fist", () -> new Equipment(210, 0x0, EquipmentSlot.WEAPON, LodMod.LIGHT_ELEMENT.get(), new ElementSet(), new ElementSet(), 0x0, 34, 0, 0, 0, 0, 0, 0, 0, false, false, false, false, 0, 0, 0, 0, 0, ItemIcon.BOXING_GLOVE, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0x0));
  public static final RegistryDelegate<Equipment> HIDDEN_FIST = EQUIPMENT_REGISTRAR.register("hidden_fist", () -> new Equipment(210, 0x0, EquipmentSlot.WEAPON, LodMod.DARK_ELEMENT.get(), new ElementSet(), new ElementSet(), 0x0, 34, 0, 0, 0, 0, 0, 0, 0, false, false, false, false, 0, 0, 0, 0, 0, ItemIcon.BOXING_GLOVE, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0x0));
  public static final RegistryDelegate<Equipment> IFRIT_FIST = EQUIPMENT_REGISTRAR.register("ifrit_fist", () -> new Equipment(400, 0x0, EquipmentSlot.WEAPON, LodMod.FIRE_ELEMENT.get(), new ElementSet(), new ElementSet(), 0x0, 53, 0, 0, 0, 0, 0, 0, 0, false, false, false, false, 0, 0, 0, 0, 0, ItemIcon.BOXING_GLOVE, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0x0));
  public static final RegistryDelegate<Equipment> LEVIATHAN_FIST = EQUIPMENT_REGISTRAR.register("leviathan_fist", () -> new Equipment(400, 0x0, EquipmentSlot.WEAPON, LodMod.WATER_ELEMENT.get(), new ElementSet(), new ElementSet(), 0x0, 53, 0, 0, 0, 0, 0, 0, 0, false, false, false, false, 0, 0, 0, 0, 0, ItemIcon.BOXING_GLOVE, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0x0));
  public static final RegistryDelegate<Equipment> GARUDA_FIST = EQUIPMENT_REGISTRAR.register("garuda_fist", () -> new Equipment(400, 0x0, EquipmentSlot.WEAPON, LodMod.WIND_ELEMENT.get(), new ElementSet(), new ElementSet(), 0x0, 53, 0, 0, 0, 0, 0, 0, 0, false, false, false, false, 0, 0, 0, 0, 0, ItemIcon.BOXING_GLOVE, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0x0));
  public static final RegistryDelegate<Equipment> TITAN_FIST = EQUIPMENT_REGISTRAR.register("titan_fist", () -> new Equipment(400, 0x0, EquipmentSlot.WEAPON, LodMod.EARTH_ELEMENT.get(), new ElementSet(), new ElementSet(), 0x0, 53, 0, 0, 0, 0, 0, 0, 0, false, false, false, false, 0, 0, 0, 0, 0, ItemIcon.BOXING_GLOVE, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0x0));
  public static final RegistryDelegate<Equipment> PHOENIX_FIST = EQUIPMENT_REGISTRAR.register("phoenix_fist", () -> new Equipment(400, 0x0, EquipmentSlot.WEAPON, LodMod.LIGHT_ELEMENT.get(), new ElementSet(), new ElementSet(), 0x0, 53, 0, 0, 0, 0, 0, 0, 0, false, false, false, false, 0, 0, 0, 0, 0, ItemIcon.BOXING_GLOVE, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0x0));
  public static final RegistryDelegate<Equipment> DIABOLOS_FIST = EQUIPMENT_REGISTRAR.register("diabolos_fist", () -> new Equipment(400, 0x0, EquipmentSlot.WEAPON, LodMod.DARK_ELEMENT.get(), new ElementSet(), new ElementSet(), 0x0, 53, 0, 0, 0, 0, 0, 0, 0, false, false, false, false, 0, 0, 0, 0, 0, ItemIcon.BOXING_GLOVE, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0x0));

  // MERU
  public static final RegistryDelegate<Equipment> TORRENTIAL_BLOW = EQUIPMENT_REGISTRAR.register("torrential_blow", () -> new Equipment(400, 0x0, EquipmentSlot.WEAPON, LodMod.WATER_ELEMENT.get(), new ElementSet(), new ElementSet(), 0x0, 35, 0, 0, 0, 0, 0, 0, 0, false, false, false, false, 0, 0, 0, 0, 0, ItemIcon.MACE, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0x0));
  public static final RegistryDelegate<Equipment> HOT_HAMMER = EQUIPMENT_REGISTRAR.register("hot_hammer", () -> new Equipment(250, 0x0, EquipmentSlot.WEAPON, LodMod.FIRE_ELEMENT.get(), new ElementSet(), new ElementSet(), 0x0, 23, 0, 0, 0, 0, 0, 0, 0, false, false, false, false, 0, 0, 0, 0, 0, ItemIcon.HAMMER, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0x0));
  public static final RegistryDelegate<Equipment> FLARE_CROZIER = EQUIPMENT_REGISTRAR.register("flare_crozier", () -> new Equipment(400, 0x0, EquipmentSlot.WEAPON, LodMod.FIRE_ELEMENT.get(), new ElementSet(), new ElementSet(), 0x0, 35, 0, 0, 0, 0, 0, 0, 0, false, false, false, false, 0, 0, 0, 0, 0, ItemIcon.HAMMER, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0x0));
  public static final RegistryDelegate<Equipment> COLD_HAMMER = EQUIPMENT_REGISTRAR.register("cold_hammer", () -> new Equipment(250, 0x0, EquipmentSlot.WEAPON, LodMod.WATER_ELEMENT.get(), new ElementSet(), new ElementSet(), 0x0, 23, 0, 0, 0, 0, 0, 0, 0, false, false, false, false, 0, 0, 0, 0, 0, ItemIcon.HAMMER, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0x0));
  public static final RegistryDelegate<Equipment> GUSTY_MALLET = EQUIPMENT_REGISTRAR.register("gusty_mallet", () -> new Equipment(210, 0x0, EquipmentSlot.WEAPON, LodMod.WIND_ELEMENT.get(), new ElementSet(), new ElementSet(), 0x0, 18, 0, 0, 0, 0, 0, 0, 0, false, false, false, false, 0, 0, 0, 0, 0, ItemIcon.HAMMER, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0x0));
  public static final RegistryDelegate<Equipment> STONE_MALLET = EQUIPMENT_REGISTRAR.register("stone_mallet", () -> new Equipment(210, 0x0, EquipmentSlot.WEAPON, LodMod.EARTH_ELEMENT.get(), new ElementSet(), new ElementSet(), 0x0, 18, 0, 0, 0, 0, 0, 0, 0, false, false, false, false, 0, 0, 0, 0, 0, ItemIcon.HAMMER, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0x0));
  public static final RegistryDelegate<Equipment> HOLY_MACE = EQUIPMENT_REGISTRAR.register("holy_mace", () -> new Equipment(210, 0x0, EquipmentSlot.WEAPON, LodMod.LIGHT_ELEMENT.get(), new ElementSet(), new ElementSet(), 0x0, 18, 0, 0, 0, 0, 0, 0, 0, false, false, false, false, 0, 0, 0, 0, 0, ItemIcon.MACE, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0x0));
  public static final RegistryDelegate<Equipment> UNHOLY_MACE = EQUIPMENT_REGISTRAR.register("unholy_mace", () -> new Equipment(210, 0x0, EquipmentSlot.WEAPON, LodMod.DARK_ELEMENT.get(), new ElementSet(), new ElementSet(), 0x0, 18, 0, 0, 0, 0, 0, 0, 0, false, false, false, false, 0, 0, 0, 0, 0, ItemIcon.MACE, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0x0));
  public static final RegistryDelegate<Equipment> ZAP_HAMMER = EQUIPMENT_REGISTRAR.register("zap_hammer", () -> new Equipment(250, 0x0, EquipmentSlot.WEAPON, LodMod.THUNDER_ELEMENT.get(), new ElementSet(), new ElementSet(), 0x0, 23, 0, 0, 0, 0, 0, 0, 0, false, false, false, false, 0, 0, 0, 0, 0, ItemIcon.HAMMER, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0x0));
  public static final RegistryDelegate<Equipment> SYLPH_HAMMER = EQUIPMENT_REGISTRAR.register("sylph_hammer", () -> new Equipment(400, 0x0, EquipmentSlot.WEAPON, LodMod.WIND_ELEMENT.get(), new ElementSet(), new ElementSet(), 0x0, 35, 0, 0, 0, 0, 0, 0, 0, false, false, false, false, 0, 0, 0, 0, 0, ItemIcon.HAMMER, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0x0));
  public static final RegistryDelegate<Equipment> GNOME_HAMMER = EQUIPMENT_REGISTRAR.register("gnome_hammer", () -> new Equipment(400, 0x0, EquipmentSlot.WEAPON, LodMod.EARTH_ELEMENT.get(), new ElementSet(), new ElementSet(), 0x0, 35, 0, 0, 0, 0, 0, 0, 0, false, false, false, false, 0, 0, 0, 0, 0, ItemIcon.HAMMER, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0x0));
  public static final RegistryDelegate<Equipment> PALADINS_MACE = EQUIPMENT_REGISTRAR.register("paladins_mace", () -> new Equipment(400, 0x0, EquipmentSlot.WEAPON, LodMod.LIGHT_ELEMENT.get(), new ElementSet(), new ElementSet(), 0x0, 35, 0, 0, 0, 0, 0, 0, 0, false, false, false, false, 0, 0, 0, 0, 0, ItemIcon.MACE, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0x0));
  public static final RegistryDelegate<Equipment> CORRUPTED_MACE = EQUIPMENT_REGISTRAR.register("corrupted_mace", () -> new Equipment(400, 0x0, EquipmentSlot.WEAPON, LodMod.DARK_ELEMENT.get(), new ElementSet(), new ElementSet(), 0x0, 35, 0, 0, 0, 0, 0, 0, 0, false, false, false, false, 0, 0, 0, 0, 0, ItemIcon.MACE, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0x0));
  public static final RegistryDelegate<Equipment> LIGHTNING_STRIKE = EQUIPMENT_REGISTRAR.register("lightning_strike", () -> new Equipment(400, 0x0, EquipmentSlot.WEAPON, LodMod.THUNDER_ELEMENT.get(), new ElementSet(), new ElementSet(), 0x0, 35, 0, 0, 0, 0, 0, 0, 0, false, false, false, false, 0, 0, 0, 0, 0, ItemIcon.HAMMER, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0x0));

  // KONGOL
  public static final RegistryDelegate<Equipment> CRAG_AXE = EQUIPMENT_REGISTRAR.register("crag_axe", () -> new Equipment(400, 0x0, EquipmentSlot.WEAPON, LodMod.EARTH_ELEMENT.get(), new ElementSet(), new ElementSet(), 0x0, 73, 0, 0, 0, 0, 0, 0, 0, false, false, false, false, 0, 0, 0, 0, 0, ItemIcon.AXE, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0x0));
  public static final RegistryDelegate<Equipment> AXE_OF_GUSTS = EQUIPMENT_REGISTRAR.register("axe_of_gusts", () -> new Equipment(210, 0x0, EquipmentSlot.WEAPON, LodMod.WIND_ELEMENT.get(), new ElementSet(), new ElementSet(), 0x0, 50, 0, 0, 0, 0, 0, 0, 0, false, false, false, false, 0, 0, 0, 0, 0, ItemIcon.AXE, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0x0));
  public static final RegistryDelegate<Equipment> TORNADO_AXE = EQUIPMENT_REGISTRAR.register("tornado_axe", () -> new Equipment(400, 0x0, EquipmentSlot.WEAPON, LodMod.WIND_ELEMENT.get(), new ElementSet(), new ElementSet(), 0x0, 73, 0, 0, 0, 0, 0, 0, 0, false, false, false, false, 0, 0, 0, 0, 0, ItemIcon.AXE, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0x0));
  public static final RegistryDelegate<Equipment> PEBBLE_AXE = EQUIPMENT_REGISTRAR.register("pebble_axe", () -> new Equipment(210, 0x0, EquipmentSlot.WEAPON, LodMod.EARTH_ELEMENT.get(), new ElementSet(), new ElementSet(), 0x0, 50, 0, 0, 0, 0, 0, 0, 0, false, false, false, false, 0, 0, 0, 0, 0, ItemIcon.AXE, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0x0));
  public static final RegistryDelegate<Equipment> MOLTEN_GREATAXE = EQUIPMENT_REGISTRAR.register("molten_greataxe", () -> new Equipment(250, 0x0, EquipmentSlot.WEAPON, LodMod.FIRE_ELEMENT.get(), new ElementSet(), new ElementSet(), 0x0, 55, 0, 0, 0, 0, 0, 0, 0, false, false, false, false, 0, 0, 0, 0, 0, ItemIcon.AXE, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0x0));
  public static final RegistryDelegate<Equipment> LAKE_GREATAXE = EQUIPMENT_REGISTRAR.register("lake_greataxe", () -> new Equipment(250, 0x0, EquipmentSlot.WEAPON, LodMod.WATER_ELEMENT.get(), new ElementSet(), new ElementSet(), 0x0, 55, 0, 0, 0, 0, 0, 0, 0, false, false, false, false, 0, 0, 0, 0, 0, ItemIcon.AXE, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0x0));
  public static final RegistryDelegate<Equipment> GLARE_BROADAXE = EQUIPMENT_REGISTRAR.register("glare_broadaxe", () -> new Equipment(210, 0x0, EquipmentSlot.WEAPON, LodMod.LIGHT_ELEMENT.get(), new ElementSet(), new ElementSet(), 0x0, 50, 0, 0, 0, 0, 0, 0, 0, false, false, false, false, 0, 0, 0, 0, 0, ItemIcon.AXE, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0x0));
  public static final RegistryDelegate<Equipment> GRAVEN_BROADAXE = EQUIPMENT_REGISTRAR.register("graven_broadaxe", () -> new Equipment(210, 0x0, EquipmentSlot.WEAPON, LodMod.DARK_ELEMENT.get(), new ElementSet(), new ElementSet(), 0x0, 50, 0, 0, 0, 0, 0, 0, 0, false, false, false, false, 0, 0, 0, 0, 0, ItemIcon.AXE, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0x0));
  public static final RegistryDelegate<Equipment> THUNDERCLAP = EQUIPMENT_REGISTRAR.register("thunderclap", () -> new Equipment(210, 0x0, EquipmentSlot.WEAPON, LodMod.THUNDER_ELEMENT.get(), new ElementSet(), new ElementSet(), 0x0, 55, 0, 0, 0, 0, 0, 0, 0, false, false, false, false, 0, 0, 0, 0, 0, ItemIcon.AXE, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0x0));
  public static final RegistryDelegate<Equipment> VOLCANO_GREATAXE = EQUIPMENT_REGISTRAR.register("volcano_greataxe", () -> new Equipment(400, 0x0, EquipmentSlot.WEAPON, LodMod.FIRE_ELEMENT.get(), new ElementSet(), new ElementSet(), 0x0, 73, 0, 0, 0, 0, 0, 0, 0, false, false, false, false, 0, 0, 0, 0, 0, ItemIcon.AXE, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0x0));
  public static final RegistryDelegate<Equipment> GREATAXE_OF_THE_SEA = EQUIPMENT_REGISTRAR.register("greataxe_of_the_sea", () -> new Equipment(400, 0x0, EquipmentSlot.WEAPON, LodMod.WATER_ELEMENT.get(), new ElementSet(), new ElementSet(), 0x0, 73, 0, 0, 0, 0, 0, 0, 0, false, false, false, false, 0, 0, 0, 0, 0, ItemIcon.AXE, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0x0));
  public static final RegistryDelegate<Equipment> SHINING_BROADAXE = EQUIPMENT_REGISTRAR.register("shining_broadaxe", () -> new Equipment(400, 0x0, EquipmentSlot.WEAPON, LodMod.LIGHT_ELEMENT.get(), new ElementSet(), new ElementSet(), 0x0, 73, 0, 0, 0, 0, 0, 0, 0, false, false, false, false, 0, 0, 0, 0, 0, ItemIcon.AXE, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0x0));
  public static final RegistryDelegate<Equipment> BROADAXE_OF_THE_DEAD = EQUIPMENT_REGISTRAR.register("broadaxe_of_the_dead", () -> new Equipment(400, 0x0, EquipmentSlot.WEAPON, LodMod.DARK_ELEMENT.get(), new ElementSet(), new ElementSet(), 0x0, 73, 0, 0, 0, 0, 0, 0, 0, false, false, false, false, 0, 0, 0, 0, 0, ItemIcon.AXE, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0x0));
  public static final RegistryDelegate<Equipment> THUNDEROUS_ROAR = EQUIPMENT_REGISTRAR.register("thunderous_roar", () -> new Equipment(400, 0x0, EquipmentSlot.WEAPON, LodMod.THUNDER_ELEMENT.get(), new ElementSet(), new ElementSet(), 0x0, 73, 0, 0, 0, 0, 0, 0, 0, false, false, false, false, 0, 0, 0, 0, 0, ItemIcon.AXE, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0x0));

  // SPECIAL RINGS
  public static final RegistryDelegate<Equipment> THIEF_CAPE = EQUIPMENT_REGISTRAR.register("thief_cape", () -> new Equipment(500, 0x0, EquipmentSlot.ACCESSORY, LodMod.NO_ELEMENT.get(), new ElementSet(), new ElementSet(), 0xb0, 2, 0, 0, 0, 0, 0, 0, 0, false, false, false, false, 0, 1, 10, 0, 0, ItemIcon.CAPE, 5, 0, 2, 2, 2, 5, 5, 0, 0, 0, 0x0));
  public static final RegistryDelegate<Equipment> THIEF_SCARF = EQUIPMENT_REGISTRAR.register("thief_scarf", () -> new Equipment(1000, 0x0, EquipmentSlot.ACCESSORY, LodMod.NO_ELEMENT.get(), new ElementSet(), new ElementSet(), 0xb0, 5, 0, 0, 0, 0, 0, 0, 0, false, false, false, false, 0, 3, 20, 0, 0, ItemIcon.SCARF, 10, 0, 5, 5, 5, 10, 10, 5, 5, 0, 0x0));
  public static final RegistryDelegate<Equipment> WINGLY_MANTLE = EQUIPMENT_REGISTRAR.register("wingly_mantle", () -> new Equipment(1500, 0x0, EquipmentSlot.ACCESSORY, LodMod.NO_ELEMENT.get(), new ElementSet(), new ElementSet(), 0xb0, 10, 0, 0, 0, 0, 0, 0, 0, false, false, false, false, 0, 5, 30, 0, 0, ItemIcon.CLOAK, 15, 0, 10, 10, 10, 15, 15, 10, 10, 0, 0x0));

  static void register(final EquipmentRegistryEvent event) { EQUIPMENT_REGISTRAR.registryEvent(event);}
}
